/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: images/mqueue.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "images/mqueue.pb-c.h"
void   mqueue_message__init
                     (MqueueMessage         *message)
{
  static const MqueueMessage init_value = MQUEUE_MESSAGE__INIT;
  *message = init_value;
}
size_t mqueue_message__get_packed_size
                     (const MqueueMessage *message)
{
  assert(message->base.descriptor == &mqueue_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mqueue_message__pack
                     (const MqueueMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mqueue_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mqueue_message__pack_to_buffer
                     (const MqueueMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mqueue_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MqueueMessage *
       mqueue_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MqueueMessage *)
     protobuf_c_message_unpack (&mqueue_message__descriptor,
                                allocator, len, data);
}
void   mqueue_message__free_unpacked
                     (MqueueMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mqueue_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mqueue_entry__init
                     (MqueueEntry         *message)
{
  static const MqueueEntry init_value = MQUEUE_ENTRY__INIT;
  *message = init_value;
}
size_t mqueue_entry__get_packed_size
                     (const MqueueEntry *message)
{
  assert(message->base.descriptor == &mqueue_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mqueue_entry__pack
                     (const MqueueEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mqueue_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mqueue_entry__pack_to_buffer
                     (const MqueueEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mqueue_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MqueueEntry *
       mqueue_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MqueueEntry *)
     protobuf_c_message_unpack (&mqueue_entry__descriptor,
                                allocator, len, data);
}
void   mqueue_entry__free_unpacked
                     (MqueueEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mqueue_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mqueue_message__field_descriptors[2] =
{
  {
    "priority",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MqueueMessage, priority),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MqueueMessage, body),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mqueue_message__field_indices_by_name[] = {
  1,   /* field[1] = body */
  0,   /* field[0] = priority */
};
static const ProtobufCIntRange mqueue_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mqueue_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MqueueMessage",
  "MqueueMessage",
  "MqueueMessage",
  "",
  sizeof(MqueueMessage),
  2,
  mqueue_message__field_descriptors,
  mqueue_message__field_indices_by_name,
  1,  mqueue_message__number_ranges,
  (ProtobufCMessageInit) mqueue_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mqueue_entry__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MqueueEntry, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxmsg",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(MqueueEntry, maxmsg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgsize",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(MqueueEntry, msgsize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "curmsgs",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(MqueueEntry, curmsgs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgs",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MqueueEntry, n_msgs),
    offsetof(MqueueEntry, msgs),
    &mqueue_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mqueue_entry__field_indices_by_name[] = {
  3,   /* field[3] = curmsgs */
  1,   /* field[1] = maxmsg */
  4,   /* field[4] = msgs */
  2,   /* field[2] = msgsize */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange mqueue_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor mqueue_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MqueueEntry",
  "MqueueEntry",
  "MqueueEntry",
  "",
  sizeof(MqueueEntry),
  5,
  mqueue_entry__field_descriptors,
  mqueue_entry__field_indices_by_name,
  1,  mqueue_entry__number_ranges,
  (ProtobufCMessageInit) mqueue_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
