/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: images/mqueue.proto */

#ifndef PROTOBUF_C_images_2fmqueue_2eproto__INCLUDED
#define PROTOBUF_C_images_2fmqueue_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct MqueueMessage MqueueMessage;
typedef struct MqueueEntry MqueueEntry;


/* --- enums --- */


/* --- messages --- */

struct  MqueueMessage
{
  ProtobufCMessage base;
  uint32_t priority;
  ProtobufCBinaryData body;
};
#define MQUEUE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mqueue_message__descriptor) \
    , 0, {0,NULL} }


struct  MqueueEntry
{
  ProtobufCMessage base;
  char *name;
  int64_t maxmsg;
  int64_t msgsize;
  int64_t curmsgs;
  size_t n_msgs;
  MqueueMessage **msgs;
};
#define MQUEUE_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mqueue_entry__descriptor) \
    , NULL, 0, 0, 0, 0,NULL }


/* MqueueMessage methods */
void   mqueue_message__init
                     (MqueueMessage         *message);
size_t mqueue_message__get_packed_size
                     (const MqueueMessage   *message);
size_t mqueue_message__pack
                     (const MqueueMessage   *message,
                      uint8_t             *out);
size_t mqueue_message__pack_to_buffer
                     (const MqueueMessage   *message,
                      ProtobufCBuffer     *buffer);
MqueueMessage *
       mqueue_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mqueue_message__free_unpacked
                     (MqueueMessage *message,
                      ProtobufCAllocator *allocator);
/* MqueueEntry methods */
void   mqueue_entry__init
                     (MqueueEntry         *message);
size_t mqueue_entry__get_packed_size
                     (const MqueueEntry   *message);
size_t mqueue_entry__pack
                     (const MqueueEntry   *message,
                      uint8_t             *out);
size_t mqueue_entry__pack_to_buffer
                     (const MqueueEntry   *message,
                      ProtobufCBuffer     *buffer);
MqueueEntry *
       mqueue_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mqueue_entry__free_unpacked
                     (MqueueEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MqueueMessage_Closure)
                 (const MqueueMessage *message,
                  void *closure_data);
typedef void (*MqueueEntry_Closure)
                 (const MqueueEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mqueue_message__descriptor;
extern const ProtobufCMessageDescriptor mqueue_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_images_2fmqueue_2eproto__INCLUDED */
